// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/auth/login.ts";
import * as $5 from "./routes/api/auth/logout.ts";
import * as $6 from "./routes/auth/api/login.ts";
import * as $7 from "./routes/auth/api/register.ts";
import * as $8 from "./routes/auth/login.tsx";
import * as $9 from "./routes/auth/register.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/landing.tsx";
import * as $12 from "./routes/user/api/[id]/index.ts";
import * as $13 from "./routes/user/api/_middleware.ts";
import * as $14 from "./routes/user/api/index.ts";
import * as $15 from "./routes/user/api/query.ts";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/auth/login.ts": $4,
    "./routes/api/auth/logout.ts": $5,
    "./routes/auth/api/login.ts": $6,
    "./routes/auth/api/register.ts": $7,
    "./routes/auth/login.tsx": $8,
    "./routes/auth/register.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/landing.tsx": $11,
    "./routes/user/api/[id]/index.ts": $12,
    "./routes/user/api/_middleware.ts": $13,
    "./routes/user/api/index.ts": $14,
    "./routes/user/api/query.ts": $15,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
